# Generated by Django 3.0.6 on 2020-06-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('created_by', models.DateTimeField(auto_now=True)),
                ('updated_by', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
